[project]
name = 'Prediction-Market'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.betting]
path = 'contracts/betting.clar'
clarity_version = 2
epoch = 2.5

[contracts.event]
path = 'contracts/event.clar'
clarity_version = 2
epoch = 2.5

[contracts.oracle]
path = 'contracts/oracle.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
